#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DobraDietaApp
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DobraDieta")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertEmployee(Employee instance);
    partial void UpdateEmployee(Employee instance);
    partial void DeleteEmployee(Employee instance);
    partial void InsertRole(Role instance);
    partial void UpdateRole(Role instance);
    partial void DeleteRole(Role instance);
    partial void InsertKlienci(Klienci instance);
    partial void UpdateKlienci(Klienci instance);
    partial void DeleteKlienci(Klienci instance);
    partial void InsertPosilek(Posilek instance);
    partial void UpdatePosilek(Posilek instance);
    partial void DeletePosilek(Posilek instance);
    partial void Inserttyp_posilku(typ_posilku instance);
    partial void Updatetyp_posilku(typ_posilku instance);
    partial void Deletetyp_posilku(typ_posilku instance);
    partial void InsertProdukty(Produkty instance);
    partial void UpdateProdukty(Produkty instance);
    partial void DeleteProdukty(Produkty instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::DobraDietaApp.Properties.Settings.Default.DobraDietaConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Employee> Employees
		{
			get
			{
				return this.GetTable<Employee>();
			}
		}
		
		public System.Data.Linq.Table<Role> Roles
		{
			get
			{
				return this.GetTable<Role>();
			}
		}
		
		public System.Data.Linq.Table<pracownik_rola> pracownik_rolas
		{
			get
			{
				return this.GetTable<pracownik_rola>();
			}
		}
		
		public System.Data.Linq.Table<Klienci> Kliencis
		{
			get
			{
				return this.GetTable<Klienci>();
			}
		}
		
		public System.Data.Linq.Table<Posilek> Posileks
		{
			get
			{
				return this.GetTable<Posilek>();
			}
		}
		
		public System.Data.Linq.Table<Posilek_produkty> Posilek_produkties
		{
			get
			{
				return this.GetTable<Posilek_produkty>();
			}
		}
		
		public System.Data.Linq.Table<typ_posilku> typ_posilkus
		{
			get
			{
				return this.GetTable<typ_posilku>();
			}
		}
		
		public System.Data.Linq.Table<Produkty> Produkties
		{
			get
			{
				return this.GetTable<Produkty>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Employees")]
	public partial class Employee : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_employee;
		
		private string _login;
		
		private string _name;
		
		private string _surname;
		
		private string _password;
		
		private System.Data.Linq.Binary _photo;
		
		private EntitySet<Posilek> _Posileks;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_employeeChanging(int value);
    partial void Onid_employeeChanged();
    partial void OnloginChanging(string value);
    partial void OnloginChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnsurnameChanging(string value);
    partial void OnsurnameChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OnphotoChanging(System.Data.Linq.Binary value);
    partial void OnphotoChanged();
    #endregion
		
		public Employee()
		{
			this._Posileks = new EntitySet<Posilek>(new Action<Posilek>(this.attach_Posileks), new Action<Posilek>(this.detach_Posileks));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_employee", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_employee
		{
			get
			{
				return this._id_employee;
			}
			set
			{
				if ((this._id_employee != value))
				{
					this.Onid_employeeChanging(value);
					this.SendPropertyChanging();
					this._id_employee = value;
					this.SendPropertyChanged("id_employee");
					this.Onid_employeeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_login", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string login
		{
			get
			{
				return this._login;
			}
			set
			{
				if ((this._login != value))
				{
					this.OnloginChanging(value);
					this.SendPropertyChanging();
					this._login = value;
					this.SendPropertyChanged("login");
					this.OnloginChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(50)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_surname", DbType="VarChar(50)")]
		public string surname
		{
			get
			{
				return this._surname;
			}
			set
			{
				if ((this._surname != value))
				{
					this.OnsurnameChanging(value);
					this.SendPropertyChanging();
					this._surname = value;
					this.SendPropertyChanged("surname");
					this.OnsurnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="VarChar(64)")]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_photo", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary photo
		{
			get
			{
				return this._photo;
			}
			set
			{
				if ((this._photo != value))
				{
					this.OnphotoChanging(value);
					this.SendPropertyChanging();
					this._photo = value;
					this.SendPropertyChanged("photo");
					this.OnphotoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Employee_Posilek", Storage="_Posileks", ThisKey="id_employee", OtherKey="id_employee")]
		public EntitySet<Posilek> Posileks
		{
			get
			{
				return this._Posileks;
			}
			set
			{
				this._Posileks.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Posileks(Posilek entity)
		{
			this.SendPropertyChanging();
			entity.Employee = this;
		}
		
		private void detach_Posileks(Posilek entity)
		{
			this.SendPropertyChanging();
			entity.Employee = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Roles")]
	public partial class Role : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_role;
		
		private string _name;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_roleChanging(int value);
    partial void Onid_roleChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    #endregion
		
		public Role()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_role", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_role
		{
			get
			{
				return this._id_role;
			}
			set
			{
				if ((this._id_role != value))
				{
					this.Onid_roleChanging(value);
					this.SendPropertyChanging();
					this._id_role = value;
					this.SendPropertyChanged("id_role");
					this.Onid_roleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.pracownik_rola")]
	public partial class pracownik_rola
	{
		
		private int _id_pracownika;
		
		private int _id_role;
		
		public pracownik_rola()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_pracownika", DbType="Int NOT NULL")]
		public int id_pracownika
		{
			get
			{
				return this._id_pracownika;
			}
			set
			{
				if ((this._id_pracownika != value))
				{
					this._id_pracownika = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_role", DbType="Int NOT NULL")]
		public int id_role
		{
			get
			{
				return this._id_role;
			}
			set
			{
				if ((this._id_role != value))
				{
					this._id_role = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Klienci")]
	public partial class Klienci : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_klient;
		
		private string _imie;
		
		private string _nazwisko;
		
		private System.Nullable<double> _wiek;
		
		private System.Nullable<double> _waga;
		
		private System.Nullable<double> _wzrost;
		
		private EntitySet<Posilek> _Posileks;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_klientChanging(int value);
    partial void Onid_klientChanged();
    partial void OnimieChanging(string value);
    partial void OnimieChanged();
    partial void OnnazwiskoChanging(string value);
    partial void OnnazwiskoChanged();
    partial void OnwiekChanging(System.Nullable<double> value);
    partial void OnwiekChanged();
    partial void OnwagaChanging(System.Nullable<double> value);
    partial void OnwagaChanged();
    partial void OnwzrostChanging(System.Nullable<double> value);
    partial void OnwzrostChanged();
    #endregion
		
		public Klienci()
		{
			this._Posileks = new EntitySet<Posilek>(new Action<Posilek>(this.attach_Posileks), new Action<Posilek>(this.detach_Posileks));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_klient", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_klient
		{
			get
			{
				return this._id_klient;
			}
			set
			{
				if ((this._id_klient != value))
				{
					this.Onid_klientChanging(value);
					this.SendPropertyChanging();
					this._id_klient = value;
					this.SendPropertyChanged("id_klient");
					this.Onid_klientChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imie", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string imie
		{
			get
			{
				return this._imie;
			}
			set
			{
				if ((this._imie != value))
				{
					this.OnimieChanging(value);
					this.SendPropertyChanging();
					this._imie = value;
					this.SendPropertyChanged("imie");
					this.OnimieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nazwisko", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nazwisko
		{
			get
			{
				return this._nazwisko;
			}
			set
			{
				if ((this._nazwisko != value))
				{
					this.OnnazwiskoChanging(value);
					this.SendPropertyChanging();
					this._nazwisko = value;
					this.SendPropertyChanged("nazwisko");
					this.OnnazwiskoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_wiek", DbType="Float")]
		public System.Nullable<double> wiek
		{
			get
			{
				return this._wiek;
			}
			set
			{
				if ((this._wiek != value))
				{
					this.OnwiekChanging(value);
					this.SendPropertyChanging();
					this._wiek = value;
					this.SendPropertyChanged("wiek");
					this.OnwiekChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_waga", DbType="Float")]
		public System.Nullable<double> waga
		{
			get
			{
				return this._waga;
			}
			set
			{
				if ((this._waga != value))
				{
					this.OnwagaChanging(value);
					this.SendPropertyChanging();
					this._waga = value;
					this.SendPropertyChanged("waga");
					this.OnwagaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_wzrost", DbType="Float")]
		public System.Nullable<double> wzrost
		{
			get
			{
				return this._wzrost;
			}
			set
			{
				if ((this._wzrost != value))
				{
					this.OnwzrostChanging(value);
					this.SendPropertyChanging();
					this._wzrost = value;
					this.SendPropertyChanged("wzrost");
					this.OnwzrostChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Klienci_Posilek", Storage="_Posileks", ThisKey="id_klient", OtherKey="id_klient")]
		public EntitySet<Posilek> Posileks
		{
			get
			{
				return this._Posileks;
			}
			set
			{
				this._Posileks.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Posileks(Posilek entity)
		{
			this.SendPropertyChanging();
			entity.Klienci = this;
		}
		
		private void detach_Posileks(Posilek entity)
		{
			this.SendPropertyChanging();
			entity.Klienci = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Posilek")]
	public partial class Posilek : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_posilku;
		
		private int _id_klient;
		
		private int _id_typ_posilku;
		
		private System.DateTime _data_posilku;
		
		private int _id_employee;
		
		private System.DateTime _data_wprowadzenia;
		
		private EntityRef<Klienci> _Klienci;
		
		private EntityRef<Employee> _Employee;
		
		private EntityRef<typ_posilku> _typ_posilku;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_posilkuChanging(int value);
    partial void Onid_posilkuChanged();
    partial void Onid_klientChanging(int value);
    partial void Onid_klientChanged();
    partial void Onid_typ_posilkuChanging(int value);
    partial void Onid_typ_posilkuChanged();
    partial void Ondata_posilkuChanging(System.DateTime value);
    partial void Ondata_posilkuChanged();
    partial void Onid_employeeChanging(int value);
    partial void Onid_employeeChanged();
    partial void Ondata_wprowadzeniaChanging(System.DateTime value);
    partial void Ondata_wprowadzeniaChanged();
    #endregion
		
		public Posilek()
		{
			this._Klienci = default(EntityRef<Klienci>);
			this._Employee = default(EntityRef<Employee>);
			this._typ_posilku = default(EntityRef<typ_posilku>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_posilku", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_posilku
		{
			get
			{
				return this._id_posilku;
			}
			set
			{
				if ((this._id_posilku != value))
				{
					this.Onid_posilkuChanging(value);
					this.SendPropertyChanging();
					this._id_posilku = value;
					this.SendPropertyChanged("id_posilku");
					this.Onid_posilkuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_klient", DbType="Int NOT NULL")]
		public int id_klient
		{
			get
			{
				return this._id_klient;
			}
			set
			{
				if ((this._id_klient != value))
				{
					if (this._Klienci.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_klientChanging(value);
					this.SendPropertyChanging();
					this._id_klient = value;
					this.SendPropertyChanged("id_klient");
					this.Onid_klientChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_typ_posilku", DbType="Int NOT NULL")]
		public int id_typ_posilku
		{
			get
			{
				return this._id_typ_posilku;
			}
			set
			{
				if ((this._id_typ_posilku != value))
				{
					if (this._typ_posilku.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_typ_posilkuChanging(value);
					this.SendPropertyChanging();
					this._id_typ_posilku = value;
					this.SendPropertyChanged("id_typ_posilku");
					this.Onid_typ_posilkuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_data_posilku", DbType="Date NOT NULL")]
		public System.DateTime data_posilku
		{
			get
			{
				return this._data_posilku;
			}
			set
			{
				if ((this._data_posilku != value))
				{
					this.Ondata_posilkuChanging(value);
					this.SendPropertyChanging();
					this._data_posilku = value;
					this.SendPropertyChanged("data_posilku");
					this.Ondata_posilkuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_employee", DbType="Int NOT NULL")]
		public int id_employee
		{
			get
			{
				return this._id_employee;
			}
			set
			{
				if ((this._id_employee != value))
				{
					if (this._Employee.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_employeeChanging(value);
					this.SendPropertyChanging();
					this._id_employee = value;
					this.SendPropertyChanged("id_employee");
					this.Onid_employeeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_data_wprowadzenia", DbType="Date NOT NULL")]
		public System.DateTime data_wprowadzenia
		{
			get
			{
				return this._data_wprowadzenia;
			}
			set
			{
				if ((this._data_wprowadzenia != value))
				{
					this.Ondata_wprowadzeniaChanging(value);
					this.SendPropertyChanging();
					this._data_wprowadzenia = value;
					this.SendPropertyChanged("data_wprowadzenia");
					this.Ondata_wprowadzeniaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Klienci_Posilek", Storage="_Klienci", ThisKey="id_klient", OtherKey="id_klient", IsForeignKey=true)]
		public Klienci Klienci
		{
			get
			{
				return this._Klienci.Entity;
			}
			set
			{
				Klienci previousValue = this._Klienci.Entity;
				if (((previousValue != value) 
							|| (this._Klienci.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Klienci.Entity = null;
						previousValue.Posileks.Remove(this);
					}
					this._Klienci.Entity = value;
					if ((value != null))
					{
						value.Posileks.Add(this);
						this._id_klient = value.id_klient;
					}
					else
					{
						this._id_klient = default(int);
					}
					this.SendPropertyChanged("Klienci");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Employee_Posilek", Storage="_Employee", ThisKey="id_employee", OtherKey="id_employee", IsForeignKey=true)]
		public Employee Employee
		{
			get
			{
				return this._Employee.Entity;
			}
			set
			{
				Employee previousValue = this._Employee.Entity;
				if (((previousValue != value) 
							|| (this._Employee.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Employee.Entity = null;
						previousValue.Posileks.Remove(this);
					}
					this._Employee.Entity = value;
					if ((value != null))
					{
						value.Posileks.Add(this);
						this._id_employee = value.id_employee;
					}
					else
					{
						this._id_employee = default(int);
					}
					this.SendPropertyChanged("Employee");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="typ_posilku_Posilek", Storage="_typ_posilku", ThisKey="id_typ_posilku", OtherKey="id_typ_posilku", IsForeignKey=true)]
		public typ_posilku typ_posilku
		{
			get
			{
				return this._typ_posilku.Entity;
			}
			set
			{
				typ_posilku previousValue = this._typ_posilku.Entity;
				if (((previousValue != value) 
							|| (this._typ_posilku.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._typ_posilku.Entity = null;
						previousValue.Posileks.Remove(this);
					}
					this._typ_posilku.Entity = value;
					if ((value != null))
					{
						value.Posileks.Add(this);
						this._id_typ_posilku = value.id_typ_posilku;
					}
					else
					{
						this._id_typ_posilku = default(int);
					}
					this.SendPropertyChanged("typ_posilku");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Posilek_produkty")]
	public partial class Posilek_produkty
	{
		
		private int _id_posilku;
		
		private int _id_produktu;
		
		public Posilek_produkty()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_posilku", DbType="Int NOT NULL")]
		public int id_posilku
		{
			get
			{
				return this._id_posilku;
			}
			set
			{
				if ((this._id_posilku != value))
				{
					this._id_posilku = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_produktu", DbType="Int NOT NULL")]
		public int id_produktu
		{
			get
			{
				return this._id_produktu;
			}
			set
			{
				if ((this._id_produktu != value))
				{
					this._id_produktu = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.typ_posilku")]
	public partial class typ_posilku : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_typ_posilku;
		
		private string _name;
		
		private EntitySet<Posilek> _Posileks;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_typ_posilkuChanging(int value);
    partial void Onid_typ_posilkuChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    #endregion
		
		public typ_posilku()
		{
			this._Posileks = new EntitySet<Posilek>(new Action<Posilek>(this.attach_Posileks), new Action<Posilek>(this.detach_Posileks));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_typ_posilku", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_typ_posilku
		{
			get
			{
				return this._id_typ_posilku;
			}
			set
			{
				if ((this._id_typ_posilku != value))
				{
					this.Onid_typ_posilkuChanging(value);
					this.SendPropertyChanging();
					this._id_typ_posilku = value;
					this.SendPropertyChanged("id_typ_posilku");
					this.Onid_typ_posilkuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="typ_posilku_Posilek", Storage="_Posileks", ThisKey="id_typ_posilku", OtherKey="id_typ_posilku")]
		public EntitySet<Posilek> Posileks
		{
			get
			{
				return this._Posileks;
			}
			set
			{
				this._Posileks.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Posileks(Posilek entity)
		{
			this.SendPropertyChanging();
			entity.typ_posilku = this;
		}
		
		private void detach_Posileks(Posilek entity)
		{
			this.SendPropertyChanging();
			entity.typ_posilku = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Produkty")]
	public partial class Produkty : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_produkty;
		
		private string _nazwa;
		
		private double _ilosc;
		
		private string _miara_domowa;
		
		private System.Nullable<double> _energia;
		
		private System.Nullable<double> _bialko;
		
		private System.Nullable<double> _tlusz;
		
		private System.Nullable<double> _weglowodany;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_produktyChanging(int value);
    partial void Onid_produktyChanged();
    partial void OnnazwaChanging(string value);
    partial void OnnazwaChanged();
    partial void OniloscChanging(double value);
    partial void OniloscChanged();
    partial void Onmiara_domowaChanging(string value);
    partial void Onmiara_domowaChanged();
    partial void OnenergiaChanging(System.Nullable<double> value);
    partial void OnenergiaChanged();
    partial void OnbialkoChanging(System.Nullable<double> value);
    partial void OnbialkoChanged();
    partial void OntluszChanging(System.Nullable<double> value);
    partial void OntluszChanged();
    partial void OnweglowodanyChanging(System.Nullable<double> value);
    partial void OnweglowodanyChanged();
    #endregion
		
		public Produkty()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_produkty", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_produkty
		{
			get
			{
				return this._id_produkty;
			}
			set
			{
				if ((this._id_produkty != value))
				{
					this.Onid_produktyChanging(value);
					this.SendPropertyChanging();
					this._id_produkty = value;
					this.SendPropertyChanged("id_produkty");
					this.Onid_produktyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nazwa", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nazwa
		{
			get
			{
				return this._nazwa;
			}
			set
			{
				if ((this._nazwa != value))
				{
					this.OnnazwaChanging(value);
					this.SendPropertyChanging();
					this._nazwa = value;
					this.SendPropertyChanged("nazwa");
					this.OnnazwaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ilosc", DbType="Float NOT NULL")]
		public double ilosc
		{
			get
			{
				return this._ilosc;
			}
			set
			{
				if ((this._ilosc != value))
				{
					this.OniloscChanging(value);
					this.SendPropertyChanging();
					this._ilosc = value;
					this.SendPropertyChanged("ilosc");
					this.OniloscChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_miara_domowa", DbType="VarChar(50)")]
		public string miara_domowa
		{
			get
			{
				return this._miara_domowa;
			}
			set
			{
				if ((this._miara_domowa != value))
				{
					this.Onmiara_domowaChanging(value);
					this.SendPropertyChanging();
					this._miara_domowa = value;
					this.SendPropertyChanged("miara_domowa");
					this.Onmiara_domowaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_energia", DbType="Float")]
		public System.Nullable<double> energia
		{
			get
			{
				return this._energia;
			}
			set
			{
				if ((this._energia != value))
				{
					this.OnenergiaChanging(value);
					this.SendPropertyChanging();
					this._energia = value;
					this.SendPropertyChanged("energia");
					this.OnenergiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bialko", DbType="Float")]
		public System.Nullable<double> bialko
		{
			get
			{
				return this._bialko;
			}
			set
			{
				if ((this._bialko != value))
				{
					this.OnbialkoChanging(value);
					this.SendPropertyChanging();
					this._bialko = value;
					this.SendPropertyChanged("bialko");
					this.OnbialkoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tlusz", DbType="Float")]
		public System.Nullable<double> tlusz
		{
			get
			{
				return this._tlusz;
			}
			set
			{
				if ((this._tlusz != value))
				{
					this.OntluszChanging(value);
					this.SendPropertyChanging();
					this._tlusz = value;
					this.SendPropertyChanged("tlusz");
					this.OntluszChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_weglowodany", DbType="Float")]
		public System.Nullable<double> weglowodany
		{
			get
			{
				return this._weglowodany;
			}
			set
			{
				if ((this._weglowodany != value))
				{
					this.OnweglowodanyChanging(value);
					this.SendPropertyChanging();
					this._weglowodany = value;
					this.SendPropertyChanged("weglowodany");
					this.OnweglowodanyChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
