<?xml version="1.0" encoding="utf-8"?><Database Name="DobraDieta" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=desktop-ejmt7jc;Initial Catalog=DobraDieta;Integrated Security=True" SettingsObjectName="DobraDietaApp.Properties.Settings" SettingsPropertyName="DobraDietaConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Employees" Member="Employees">
    <Type Name="Employee">
      <Column Name="id_employee" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="login" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="surname" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="password" Type="System.String" DbType="VarChar(64)" CanBeNull="true" />
      <Column Name="photo" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="Employee_pracownik_rola" Member="pracownik_rolas" ThisKey="id_employee" OtherKey="id_pracownika" Type="pracownik_rola" />
      <Association Name="Employee_Posilek" Member="Posileks" ThisKey="id_employee" OtherKey="id_employee" Type="Posilek" />
    </Type>
  </Table>
  <Table Name="dbo.Roles" Member="Roles">
    <Type Name="Role">
      <Column Name="id_role" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Role_pracownik_rola" Member="pracownik_rolas" ThisKey="id_role" OtherKey="id_role" Type="pracownik_rola" />
    </Type>
  </Table>
  <Table Name="dbo.pracownik_rola" Member="pracownik_rolas">
    <Type Name="pracownik_rola">
      <Column Name="id_pracownika" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_role" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Employee_pracownik_rola" Member="Employee" ThisKey="id_pracownika" OtherKey="id_employee" Type="Employee" IsForeignKey="true" />
      <Association Name="Role_pracownik_rola" Member="Role" ThisKey="id_role" OtherKey="id_role" Type="Role" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Klienci" Member="Kliencis">
    <Type Name="Klienci">
      <Column Name="id_klient" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="imie" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="nazwisko" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="wiek" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="waga" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="wzrost" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="Klienci_Posilek" Member="Posileks" ThisKey="id_klient" OtherKey="id_klient" Type="Posilek" />
    </Type>
  </Table>
  <Table Name="dbo.Posilek" Member="Posileks">
    <Type Name="Posilek">
      <Column Name="id_posilku" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_klient" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_typ_posilku" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="data_posilku" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="id_employee" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="data_wprowadzenia" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Association Name="Posilek_Posilek_produkty" Member="Posilek_produkties" ThisKey="id_posilku" OtherKey="id_posilku" Type="Posilek_produkty" />
      <Association Name="Klienci_Posilek" Member="Klienci" ThisKey="id_klient" OtherKey="id_klient" Type="Klienci" IsForeignKey="true" />
      <Association Name="Employee_Posilek" Member="Employee" ThisKey="id_employee" OtherKey="id_employee" Type="Employee" IsForeignKey="true" />
      <Association Name="typ_posilku_Posilek" Member="typ_posilku" ThisKey="id_typ_posilku" OtherKey="id_typ_posilku" Type="typ_posilku" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Posilek_produkty" Member="Posilek_produkties">
    <Type Name="Posilek_produkty">
      <Column Name="id_posilku" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_produktu" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Posilek_Posilek_produkty" Member="Posilek" ThisKey="id_posilku" OtherKey="id_posilku" Type="Posilek" IsForeignKey="true" />
      <Association Name="Produkty_Posilek_produkty" Member="Produkty" ThisKey="id_produktu" OtherKey="id_produkty" Type="Produkty" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.typ_posilku" Member="typ_posilkus">
    <Type Name="typ_posilku">
      <Column Name="id_typ_posilku" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="typ_posilku_Posilek" Member="Posileks" ThisKey="id_typ_posilku" OtherKey="id_typ_posilku" Type="Posilek" />
    </Type>
  </Table>
  <Table Name="dbo.Produkty" Member="Produkties">
    <Type Name="Produkty">
      <Column Name="id_produkty" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nazwa" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ilosc" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="miara_domowa" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="energia" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="bialko" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="tlusz" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="weglowodany" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="Produkty_Posilek_produkty" Member="Posilek_produkties" ThisKey="id_produkty" OtherKey="id_produktu" Type="Posilek_produkty" />
    </Type>
  </Table>
</Database>